[build-system]
requires = [
    "setuptools>=42",
    "wheel",
    "numpy",
    "pandas",
    "scipy",
    "cython"
]
build-backend = "setuptools.build_meta"

[tool.poetry.dependencies]
python = '^3.7'
numpy = '^1.19.0'
pandas = '^1.0.0'
scipy = '^1.6.0'